Workshop/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Workshop.Models;
using Workshop.ViewModels;

namespace Workshop.Controllers
{
    public class CarController : Controller
    {
        private readonly WorkshopContext _context;

        public CarController(WorkshopContext context)
        {
            _context = context;
        }

        public IActionResult ListofCustomers()
        {
            var model = new RegisterCarViewModel();
            model.CustomerList = _context.Customers.ToList();

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RegisterCar(RegisterCarViewModel model)
        {
            if (ModelState.IsValid)
            {
                var car = new Cars
                {
                    CustomerId = model.Customers.CustomerId,
                    CarId = model.Cars.CarId
                };

                _context.Cars.Add(car);
                _context.SaveChanges();
                TempData["Operation"] = "Car Registration Successful.";
                return RedirectToAction("Index", "Home", TempData);
            }

            return View(model);
        }
    }
}

Workshop/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;
using Workshop.Models;
using Workshop.ViewModels;

namespace Workshop.Controllers
{
    public class CustomerController : Controller
    {
        private readonly WorkshopContext _context;

        public CustomerController(WorkshopContext context)
        {
            _context = context;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Register(RegisterCustomerViewModel user)
        {
            if (ModelState.IsValid)
            {
                var customer = new Customers
                {
                    Firstname = user.Firstname,
                    Lastname = user.Lastname,
                    SocialSecurityNumber = user.SocialSecurityNumber,
                    Address = user.Address
                };

                _context.Customers.Add(customer);
                _context.SaveChanges();
                TempData["Operation"] = "Customer Registration Successful.";
                return RedirectToAction("Index", "Home", TempData);
            }

            return View(user);
        }
    }
}

Workshop/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Workshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="btn btn-light navbar-btn" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="btn btn-light navbar-btn" style="margin-left: 5px;" asp-controller="Customer" asp-action="Register">Register Customer</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-light navbar-btn" style="margin-left: 5px;" asp-controller="Car" asp-action="ListofCustomers">Register Car</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-light navbar-btn" style="margin-left: 5px;" asp-controller="Schedule" asp-action="Schedule">Schedule Repair</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-light navbar-btn" style="margin-left: 5px;" asp-controller="Schedule" asp-action="Remove">Remove Appointment</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-light navbar-btn" style="margin-left: 5px;" asp-controller="Account" asp-action="LogOff">Logout @User.Identity.Name.ToUpper()</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn btn-light navbar-btn" style="margin-left: 5px;" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-light navbar-btn" style="margin-left: 5px;" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Workshop - Built by <a href="https://www.linkedin.com/in/ludwigj/">Ludwig</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>